version: '3.8'

services:
  django:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app  
    depends_on:
      - tor

  tor:
    image: dperson/torproxy  
    ports:
      - "9050:9050"